=== Proxyfil/Portfolio/.astro/collections/staticData.schema.json
{
  "$ref": "#/definitions/staticData",
  "definitions": {
    "staticData": {
      "type": "object",
      "properties": {
        "profileImage": {
          "type": "string"
        },
        "profileAlt": {
          "type": "string"
        },
        "profileLink": {
          "type": "string"
        },
        "profileTitle": {
          "type": "string"
        },
        "profileName": {
          "type": "string"
        },
        "github": {
          "type": "string",
          "format": "uri"
        },
        "githubText": {
          "type": "string"
        },
        "portfolioImage": {
          "type": "string"
        },
        "email": {
          "type": "string",
          "format": "email"
        },
        "linkedin": {
          "type": "string",
          "format": "uri"
        },
        "instagram": {
          "type": "string",
          "format": "uri"
        },
        "youtube": {
          "type": "string",
          "format": "uri"
        },
        "alias": {
          "type": "string"
        },
        "contactSectionTitle": {
          "type": "string"
        },
        "contactSectionSubtitle": {
          "type": "string"
        },
        "contactSectionButtonText": {
          "type": "string"
        },
        "contactSectionButtonIcon": {
          "type": "string"
        },
        "techsTitle": {
          "type": "string"
        },
        "instagramIconName": {
          "type": "string"
        },
        "youtubeIconName": {
          "type": "string"
        },
        "githubIconName": {
          "type": "string"
        },
        "linkedinIconName": {
          "type": "string"
        },
        "emailIconName": {
          "type": "string"
        },
        "$schema": {
          "type": "string"
        }
      },
      "required": [
        "profileImage",
        "profileAlt",
        "profileLink",
        "profileTitle",
        "profileName",
        "github",
        "githubText",
        "portfolioImage",
        "email",
        "linkedin",
        "instagram",
        "youtube",
        "alias",
        "contactSectionTitle",
        "contactSectionSubtitle",
        "contactSectionButtonText",
        "contactSectionButtonIcon",
        "techsTitle",
        "instagramIconName",
        "youtubeIconName",
        "githubIconName",
        "linkedinIconName",
        "emailIconName"
      ],
      "additionalProperties": false
    }
  },
  "$schema": "http://json-schema.org/draft-07/schema#"
}

=== Proxyfil/Portfolio/src/content/staticData/allStaticData.json
{
  "profileImage": "/images/proxyfil.webp",
  "profileAlt": "Photo of Pierre-Louis Leclerc (Proxyfil) for the blog",
  "profileLink": "/about-me",
  "profileTitle": "DevOps Engineer Student",
  "profileName": "Pierre-Louis Leclerc",
  "github": "https://github.com/proxyfil",
  "githubText": "Want to see my code?",
  "portfolioImage": "/images/portfolio.webp",
  "email": "leclerc.pierre-louis@gmail.com",
  "linkedin": "https://www.linkedin.com/in/pierre-louis-leclerc/",
  "instagram": "https://www.instagram.com/pierrelouisirl/",
  "youtube": "https://www.youtube.com/@proxyfil4036",
  "alias": "Proxyfil",
  "contactSectionTitle": "Ready to take your idea to the next level?",
  "contactSectionSubtitle": "Let's work together.",
  "contactSectionButtonText": "Contact Me",
  "contactSectionButtonIcon": "paperplane",
  "techsTitle": "TECHS",
  "instagramIconName": "instagram",
  "youtubeIconName": "youtube",
  "githubIconName": "github",
  "linkedinIconName": "linkedin",
  "emailIconName": "envelope"
}
